export const types = {
    USER_SIGNUP: 'user/signup',
    USER_LOGIN: 'user/login',
    USER_AUTH_GOOGLE: 'user/authGoogle',
    USER_UPDATE: 'user/update',
    GET_PROFILE: 'user/getProfile',
    GET_VIEWABLE_PROFILE: 'user/getViewableProfile',
    USER_LOGOUT: 'user/logout',
    BLOG_SAVE: 'blog/save',
    BLOG_DELETE: 'blog/delete',
    BLOG_GET_IMAGES_UNSPLASH: 'blog/getImagesUnsplash',
    GET_ALL_BLOGS: 'blog/getAll',
    GET_USER_BLOGS: 'blog/getUserBlogs',
    GET_BLOG_BY_ID: 'blog/getBlogById',
    GET_CURRENT_BLOG_BY_ID: 'blog/getCurrentBlogById',
};